### ISSUE TITLE
question about  'lemo/normalization.pkl'

### ISSUE THREAD

**Issue by coralemon** [scenediffuser/Scene-Diffuser#11]
I notice this code in dataloader:
self.normalizer = NormalizerPoseMotion((xmin, xmax)) with 'lemo/normalization.pkl'
and I wonder what is this for and the how to get the parameters in normalization.pkl ( I don't find relevant code in LEMO ) ?

**Comment by Silverster98** [comment]
> I notice this code in dataloader: self.normalizer = NormalizerPoseMotion((xmin, xmax)) with 'lemo/normalization.pkl' and I wonder what is this for and the how to get the parameters in normalization.pkl ( I don't find relevant code in LEMO ) ?

This is the normalization parameter, containing mean and std. They are directly derived from the mean and std of all pose data.
