### ISSUE TITLE
Question about variable σ in Dexterous Grasp Generation for 3D Objects

### ISSUE THREAD

**Issue by Trav1slaflame** [scenediffuser/Scene-Diffuser#15]
Hi, thanks for your great work. 

I have an issue with the **variable σ** on **Tab.3**. In your released code, test results (Success rate, Diversity and Collision) are computed in the same way as GendexGrasp. However, on Tab. 3 and Tab. A3, **σ** is used to compute success rate, which is different from the released code.

May I ask if test code for reproducing Tab. 3 and Tab. A3 will be released? Or if test results using the released test.py can be shared?
 
And what's the difference between the diversity metric you presented in this paper and the diversity metric proposed by GenDexGrasp, which you also used in your ablation experiments? Can you elaborate more about the function of the diversity metric you presented in this paper?

Thanks for your time.

**Comment by Xiaoyao-Li** [comment]
Sorry for the late reply, and thanks for your interest in our work.

You can find the all testing code about grasping generation task in the [obj branch](https://github.com/scenediffuser/Scene-Diffuser/tree/obj?tab=readme-ov-file#test-quantitative-evaluation-2). The μ and σ used in testing code correspond to the mean and variance statistics of shadowhand grasping poses in the [MultiDex](https://github.com/tengyu-liu/GenDexGrasp) dataset. You can easily obtain these numbers and then calculate the grasping success rate within different multiples of the variance range.

Regarding your question about the diversity metric, I think it's a valid point. If we only consider the variance of grasping poses as diversity, it's challenging to reflect the quality of the grasping poses. For example, a randomly generated grasping pose may have a high variance but low quality. However, we cannot consider a random strategy as diverse. Therefore, we introduced the diversity metric in Table 3 to reflect the generation of high-quality diverse samples by the model. We believe that only when the quality of the generated samples is within a certain range can the variance of the generated samples effectively reflect diversity.

Feel free to continue the discussion if you have any other questions or thoughts~
