### ISSUE TITLE
Motion generation in custom 3D scenes

### ISSUE THREAD

**Issue by stephan000** [scenediffuser/Scene-Diffuser#16]
What steps are required to generate motion in a custom 3D scene?

I have already performed the preprocessing to adapt it to the PROX data structure.
I tried to modify the code based on [datasets/lemo_motion.py](https://github.com/scenediffuser/Scene-Diffuser/blob/main/datasets/lemo_motion.py), but the motion generation could not be performed because there was no LEMO data corresponding to the custom scene.
https://github.com/scenediffuser/Scene-Diffuser/blob/main/datasets/lemo_motion.py#L155

LEMO data seems to be used as a ground truth, but is it necessary if quantitative evaluation is not required?

**Comment by Silverster98** [comment]
In this case, I think you should modify the code slightly. A simple way may be to set the motion-related parameters as zeros (treat them as placeholders).

**Comment by stephan000** [comment]
Thanks for your response. I'll try it.

**Comment by xjchao7** [comment]
> In this case, I think you should modify the code slightly. A simple way may be to set the motion-related parameters as zeros (treat them as placeholders).

I have the same problem,  could you please describe in detail which parameters should be set? Thank you！

**Comment by Silverster98** [comment]
Just set the motion parameters in the [`LEMOMotion`](https://github.com/scenediffuser/Scene-Diffuser/blob/main/datasets/lemo_motion.py#L191) dataset as zeros (but using the same array shape), which will be ignored by the inference process.
