### ISSUE TITLE
No such file or directory: 'assets/urdf/urdf_assets_meta.json'

### ISSUE THREAD

**Issue by Droliven** [scenediffuser/Scene-Diffuser#17]
When running Sample (Qualitative Visualization) of Task-3: Dexterous Grasp Generation for 3D Objects, it throws an error：No such file or directory: 'assets/urdf/urdf_assets_meta.json'

**Comment by GaoLon** [comment]
I am experiencing the same error. May I ask how you solved it? Thanks! @Droliven
