### ISSUE TITLE
Questions about the motion generation.

### ISSUE THREAD

**Issue by xjchao7** [scenediffuser/Scene-Diffuser#18]
Thank you for your perfect work. I have questions about the motion generation. Can I specify starting and ending human pose to generate intermediate motion? Do I need to retrain or do I just use the trained model？

**Comment by Silverster98** [comment]
Our motion generation supports two settings: (1) without using the starting position as a condition, and (2) using the starting position as a condition. If you want to specify both the starting and ending human poses, it is recommended to retrain the model by specifying both start and end as conditions.

Alternatively, you can use the diffusion inpainting capability with our pre-trained model to achieve this goal, although the results may be uncertain.
