### ISSUE TITLE
Question about the device.

### ISSUE THREAD

**Issue by xjchao7** [scenediffuser/Scene-Diffuser#19]
Thank you for your perfect work. I wanna ask could i test the motion generation part on V100 16G device ？  What's more, if the test code supports multi-gpu?

Thank you very much.

**Comment by Silverster98** [comment]
> Thank you for your perfect work. I wanna ask could i test the motion generation part on V100 16G device ？ What's more, if the test code supports multi-gpu?
> 
> Thank you very much.

Yes, you can test using a V100 16G device. The test script doesn't support multiple GPUs.

**Comment by xjchao7** [comment]
> > Thank you for your perfect work. I wanna ask could i test the motion generation part on V100 16G device ？ What's more, if the test code supports multi-gpu?
> > Thank you very much.
> 
> Yes, you can test using a V100 16G device. The test script doesn't support multiple GPUs.

Thanks a lot!
