### ISSUE TITLE
Question about the motion generation.

### ISSUE THREAD

**Issue by xjchao7** [scenediffuser/Scene-Diffuser#20]
I wanna ask could i change the start pose in the motion generation test process? How could i change the start pose? Thank you very much.

**Comment by Silverster98** [comment]
You should modify the dataloader. Our code directly loads motion from PROX and segments them into fixed horizons, then uses the first frame as the condition. The key code is here: https://github.com/scenediffuser/Scene-Diffuser/blob/main/datasets/transforms.py#L64-L66

If you want to change the start pose, the simplest way may be to directly change this `data[start]` using your pose.

**Comment by xjchao7** [comment]
> You should modify the dataloader. Our code directly loads motion from PROX and segments them into fixed horizons, then uses the first frame as the condition. The key code is here: https://github.com/scenediffuser/Scene-Diffuser/blob/main/datasets/transforms.py#L64-L66
> 
> If you want to change the start pose, the simplest way may be to directly change this `data[start]` using your pose.
Got it! Thank you.
