### ISSUE TITLE
Question about dexhand pose generation

### ISSUE THREAD

**Issue by bb0928** [scenediffuser/Scene-Diffuser#21]
Hello, thanks for your excellent work.
However, when i am following instruction of task 3, i have encountered this error:

(scenediff) xinglj@user-SYS-4029GP-TRT:/data/xinglj/Scene-Diffuser$ bash scripts/grasp_gen_ur/train.sh xlj01
/data/xinglj/miniconda3/envs/scenediff/lib/python3.8/site-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the `__init__` method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from models.visualizer import create_visualizer
  File "/data/xinglj/Scene-Diffuser/models/visualizer.py", line 133, in <module>
    class MotionGenVisualizer():
  File "/data/xinglj/Scene-Diffuser/utils/registry.py", line 61, in deco
    self._do_register(name, func_or_class)
  File "/data/xinglj/Scene-Diffuser/utils/registry.py", line 45, in _do_register
    assert (
AssertionError: An object named '<lambda>' was already registered in 'Visualizer' registry!

could you please offer any help about this? many thanks.

**Comment by Silverster98** [comment]
Hi, which version of PyTorch are you using? If you're using PyTorch 2, the error might be related to this issue: https://github.com/scenediffuser/Scene-Diffuser/issues/8

**Comment by bb0928** [comment]
thanks a lot, will try it.
by the way, there's another question about the figure 5 in your paper. how can you export the mesh of shadow? thanks.

**Comment by bb0928** [comment]
I have found the corresponding function. Thanks.
