### ISSUE TITLE
how can i know the meaning of shadow qpos parameters?

### ISSUE THREAD

**Issue by bb0928** [scenediffuser/Scene-Diffuser#22]
thanks for your work.
when i was looking the handmodel.py script, there is a function get_meshes_from_q(self, q=None, i=0).
the expected input of q is 33 dim, however, other project use 30-dim qpos to represent the pose of shadow hand.
how can i know what those 33-dim params mean? Many thanks.

**Comment by Xiaoyao-Li** [comment]
The shadow's qpos consists of a 9-dimensional q_global and a 24-dimensional q_local. Similar to other projects, the 24-dimensional q_local represents the angles of each joint. For q_global, the first 3 dimensions correspond to the global pose's xyz-position, while the last 6 dimensions represent the global pose's 6D rotation.

**Comment by bb0928** [comment]
thanks for your reply but i still didn't understand how to use 6d-parameter to represent rotation? I can only understand axis-angle(3d), euler(3d), and rotation matrix(9d). could you please explain this briefly?

**Comment by bb0928** [comment]
I have found the function get_rot6d_from_rpy(). thanks, I will close this issue.

**Comment by bb0928** [comment]
> The shadow's qpos consists of a 9-dimensional q_global and a 24-dimensional q_local. Similar to other projects, the 24-dimensional q_local represents the angles of each joint. For q_global, the first 3 dimensions correspond to the global pose's xyz-position, while the last 6 dimensions represent the global pose's 6D rotation.

Sorry for bothering again, i am now wondering what does 'global' mean in your q_global, is it the trans and rot of 'forearm'?

**Comment by Xiaoyao-Li** [comment]
Exactly, considering that the forearm link is the base link of the shadowhand URDF, q_global refers to the transformation of this URDF in the world coordinate frame.

**Comment by bb0928** [comment]
OK thanks so much.
