### ISSUE TITLE
Abnormal planning results

### ISSUE THREAD

**Issue by xizaoqu** [scenediffuser/Scene-Diffuser#3]
When I ran this command "bash scripts/path_planning/sample.sh ./outputs/2022-11-25_20-57-28_Path_ddm4_LR1e-4_E100_REL/ OPT PLA", nearly all outputs are abnormal. Any suggestion?
![image](https://user-images.githubusercontent.com/45515569/230816442-fa67af5c-2497-483e-86a9-4dbb285a640e.png)

**Comment by Silverster98** [comment]
The `sample.sh` script only samples trajectories with a fixed horizon conditioned on the given start position and scene, so it doesn't produce the planning results. If you want to visualize the planning results, just use the `plan.sh` script as the provided [command](https://github.com/scenediffuser/Scene-Diffuser#test-quantitative-evaluation-2).
