### ISSUE TITLE
The training set used by the pre-trained scene encoder

### ISSUE THREAD

**Issue by 1341828568** [scenediffuser/Scene-Diffuser#4]
Thank you very much for your excellent work!

For scene encoder pre-training, i wonder if you used all the scenes from the scannet or only the scenes used for this task.

cheers!

**Comment by Silverster98** [comment]
I used the ScanNet dataset for scene encoder pre-training. But I didn't use all the scenes; instead, I re-split the scenes with id from `scene0000_00` to `scene0706_00` into the train, validate, and test sets. If you want, you can use all the scenes to train your own scene encoder.

**Comment by 1341828568** [comment]
I see! 
Thank you so much!
