### ISSUE TITLE
I encountered the following two errors repeatedly when installing the https://github.com/Silverster98/pointops package. How can I solve them

### ISSUE THREAD

**Issue by ohman66** [scenediffuser/Scene-Diffuser#5]
(3d) D:\Scene-Diffuser>pip install "git+https://github.com/Silverster98/pointops"
Collecting git+https://github.com/Silverster98/pointops
  Cloning https://github.com/Silverster98/pointops to c:\users\tony\appdata\local\temp\pip-req-build-_chb1j3f
  Running command git clone --filter=blob:none --quiet https://github.com/Silverster98/pointops 'C:\Users\tony\AppData\Local\Temp\pip-req-build-_chb1j3f'
  Resolved https://github.com/Silverster98/pointops to commit 86c68b1e63092152b4ab14ff09b832c5d2d0dc97
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tony\AppData\Local\Temp\pip-req-build-_chb1j3f\setup.py", line 9, in <module>
          flag for flag in opt.split() if flag != '-Wstrict-prototypes'
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(3d) D:\Scene-Diffuser>pip install "git+https://github.com/Silverster98/pointops"
Collecting git+https://github.com/Silverster98/pointops
  Cloning https://github.com/Silverster98/pointops to c:\users\tony\appdata\local\temp\pip-req-build-m97mzi9q
  Running command git clone --filter=blob:none --quiet https://github.com/Silverster98/pointops 'C:\Users\tony\AppData\Local\Temp\pip-req-build-m97mzi9q'
  fatal: unable to access 'https://github.com/Silverster98/pointops/': Recv failure: Connection was reset
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/Silverster98/pointops 'C:\Users\tony\AppData\Local\Temp\pip-req-build-m97mzi9q' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Silverster98/pointops 'C:\Users\tony\AppData\Local\Temp\pip-req-build-m97mzi9q' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Silverster98** [comment]
I recommend running the code on Ubuntu. There may be some troubles in installing dependencies on Windows.
