### ISSUE TITLE
Missing scripts/grasp_gen_ur?

### ISSUE THREAD

**Issue by EAST-J** [scenediffuser/Scene-Diffuser#9]
It seems the scrips for grasp generation are missing?

**Comment by HYing268** [comment]
How do you solve this problem?

**Comment by EAST-J** [comment]
> How do you solve this problem?

Refer to https://github.com/scenediffuser/Scene-Diffuser#task-3-dexterous-grasp-generation-for-3d-objects, you need to switch to the obj branch
